name: KRandomTeleport
version: 1.0.134
main: com.kmcguire.KRandomTeleport.P
authors: [Leonard Kevin McGuire Jr]
softdepend: [Herochat]
commands:
    f:
      description: The interface to the faction plugin.
    resetwa:
      description: Reset world anchor specified with X Y Z